name: Security Tests

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read
  id-token: write

jobs:
  security-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Install SecTester dependencies
      run: npm install --save-dev @sectester/core @sectester/repeater @sectester/scan @sectester/runner

    - name: Create vars.env file
      run: |
        echo "MYSQL_USER=dvna" >> vars.env
        echo "MYSQL_DATABASE=dvna" >> vars.env
        echo "MYSQL_PASSWORD=passw0rd" >> vars.env
        echo "MYSQL_RANDOM_ROOT_PASSWORD=yes" >> vars.env

    - name: Start application
      run: |
        docker compose up -d
        until nc -zv 127.0.0.1 9090; do sleep 1; done

    - name: Configure Bright credentials
      uses: ./.github/workflows/composite/configure-bright-credentials
      with:
        BRIGHT_HOSTNAME: development.playground.brightsec.com
        BRIGHT_PROJECT_ID: dzZUZGaqqVhvHnZnjfXUoP
        BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}

    - name: Run security tests
      env:
        BRIGHT_HOSTNAME: development.playground.brightsec.com
        BRIGHT_PROJECT_ID: dzZUZGaqqVhvHnZnjfXUoP
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRIGHT_TOKEN: ${{ env.BRIGHT_TOKEN }}
        BRIGHT_TARGET_URL: http://127.0.0.1:9090
      run: |
        node --experimental-transform-types --experimental-strip-types --experimental-detect-module \
        --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning \
        --test-force-exit --test .brightsec/tests/*.test.ts --test-concurrency=4

    - name: Shutdown application
      if: always()
      run: docker compose down